-- ═══════════════════════════════════════════════════════════════
-- Process 800 — Migration 001 — DEPRECATED
-- ═══════════════════════════════════════════════════════════════
-- DEPRECATED 2026-05-12 — Single-tier model adopted.
-- The stale `client` and `client_error` tables defined here are
-- superseded by `clients` and `clients_error` managed by bp.840
-- (BAR-178). See Barton-Processes/factory/client/840-client-record-key/.
-- svg-d1-client.clients is the canonical D1 client table.
-- DO NOT RUN this migration against any live database.
-- ═══════════════════════════════════════════════════════════════
--
-- Original body archived below for reference only.
-- ─────────────────────────────────────────────────────────────
--
-- CREATE TABLE IF NOT EXISTS client ( ... ); -- stale schema
-- CREATE TABLE IF NOT EXISTS client_error ( ... ); -- stale schema
-- ═══════════════════════════════════════════════════════════════
