-- ═══════════════════════════════════════════════════════════════
-- Process 800 — Migration 002 — DEPRECATED
-- ═══════════════════════════════════════════════════════════════
-- DEPRECATED 2026-05-12 — Single-tier model adopted.
-- No Neon clnt.* vault schema. svg-d1-client.clients is canonical.
-- CL Neon is READ ONLY (cl.company_identity). Never written by bp.800.
-- DO NOT RUN this migration against any database.
-- ═══════════════════════════════════════════════════════════════
--
-- Original body: created clnt schema + clnt.client + clnt.client_error
-- in Neon for a two-tier vault model that has been retired.
-- ═══════════════════════════════════════════════════════════════
